/* tslint:disable */
/* eslint-disable */
import { CircunscripcionDto } from './circunscripcion-dto';
export interface InformeRenacDto {
  activo?: null | boolean;
  archivado?: null | boolean;
  circunscripcion?: CircunscripcionDto;
  constanciaAnotacionArchivo?: null | string;
  constanciaAnotacionBase64?: null | string;
  constanciaAnotacionFirmadaArchivo?: null | string;
  constanciaAnotacionFirmadaArchivo64?: null | string;
  constanciaAnotacionFirmadaFecha?: null | string;
  descripcion?: null | string;
  esDerivado?: null | boolean;
  estadoAnotacion?: null | string;
  estadoDerivacion?: null | string;
  estadoSsiat?: null | string;
  evaluacionFavorable?: null | boolean;
  evidenciaAnotacionArchivo?: null | string;
  evidenciaAnotacionArchivoBase64?: null | string;
  evidenciaAnotacionFecha?: null | string;
  evidenciaSolicitudArchivo?: null | string;
  evidenciaSolicitudArchivoBase64?: null | string;
  evidenciaSolicitudFecha?: null | string;
  fecha?: null | string;
  fechaMod?: null | string;
  fechaReg?: null | string;
  fechaSolicitudInformacion?: null | string;
  filtro?: null | string;
  idCircunscripcion?: null | number;
  idEstadoDerivacion?: null | number;
  idInformeRenac?: null | number;
  informeAnotacionBase64?: null | string;
  informeFavorableArchivo?: null | string;
  informeFavorableArchivoBase64?: null | string;
  informeFavorableFecha?: null | string;
  informeFavorableNumero?: null | string;
  listaInformesRenac?: null | string;
  nombreinformesustento?: null | string;
  numero?: null | string;
  oficioAnotacionArchivo?: null | string;
  oficioAnotacionArchivoBase64?: null | string;
  oficioAnotacionFecha?: null | string;
  oficioAnotacionNumero?: null | string;
  oficioSolicitudArchivo?: null | string;
  oficioSolicitudArchivoBase64?: null | string;
  oficioSolicitudFecha?: null | string;
  oficioSolicitudNumero?: null | string;
  pageNumber?: number;
  pageSize?: number;
  procesoAnotacionCerrado?: null | boolean;
  respuestaGoreArchivo?: null | string;
  respuestaGoreBase64?: null | string;
  respuestaGoreFecha?: null | string;
  respuestaGoreNumero?: null | string;
  rownum?: number;
  solicitudDiasTranscurridos?: null | string;
  solicitudGore?: null | boolean;
  urlProyectoMemoEspSsiat?: null | string;
  urlProyectoMemoSubSsiat?: null | string;
  urlRespuestaGore?: null | string;
  urlinformesustento?: null | string;
  usuarioMod?: null | string;
  usuarioReg?: null | string;
}
